### ISSUE TITLE
Web error

### ISSUE THREAD

**Issue by arall** [smythtech/WifiProbeMapper#1]
I'm getting this error when I try to reach the web server:

> can upgrade only to websocket

**Comment by smythtech** [comment]
Hi arall,

I'm guessing you were trying to access http://127.0.0.1:8888 in the browser. This is the address for the websocket rather than the web interface. Once the server has started you'll need to open the index.html page with a browser by either right clicking on it or running a command like 'firefox index.html'. I've updated the readme to avoid confusion in the future.
